defaults:
  - _self_
  - model: gpt4o-mini
  - evaluation: putnambench
  - prompts: default

# Global configurations
project:
  name: ftpevals
  output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  log_dir: ${project.output_dir}/logs

# General settings
seed: 42
debug: false

# Hydra configurations
hydra:
  run:
    dir: ${project.output_dir}
  job:
    chdir: true 